# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [2]:
tf.__version__

'1.13.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# Exploratory Data Analysis

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])


In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
df = pd.DataFrame(X)

In [13]:
df

0  1  2    3  4   5   6        7  8  9  10       11
0     1  0  0  619  0  42   2        0  1  1  1   101349
1     0  0  1  608  0  41   1  83807.9  1  0  1   112543
2     1  0  0  502  0  42   8   159661  3  1  0   113932
3     1  0  0  699  0  39   1        0  2  0  0  93826.6
4     0  0  1  850  0  43   2   125511  1  1  1  79084.1
...  .. .. ..  ... ..  ..  ..      ... .. .. ..      ...
9995  1  0  0  771  1  39   5        0  2  1  0  96270.6
9996  1  0  0  516  1  35  10  57369.6  1  1  1   101700
9997  1  0  0  709  0  36   7        0  1  0  1  42085.6
9998  0  1  0  772  1  42   3  75075.3  2  1  0  92888.5
9999  1  0  0  792  0  28   4   130143  1  1  0  38190.8

[10000 rows x 12 columns]

In [14]:
pip install neupy

In [15]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import StratifiedKFold
import pandas as pd
from neupy.algorithms import PNN

In [16]:
skfold = StratifiedKFold(n_splits=10)

for i, (train, test) in enumerate(skfold.split(X, y), start=1):
    x_train, x_test = X[train], X[test]
    y_train, y_test = y[train], y[test]

    pnn_network = PNN(std=0.1, verbose=False)
    pnn_network.train(x_train, y_train)
    result = pnn_network.predict(x_test)

    n_predicted_correctly = np.sum(result == y_test)
    n_test_samples = test.size

    print("Test #{:<2}: Guessed {} out of {}".format(
        i, n_predicted_correctly, n_test_samples))

Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000
Test #10: Guessed 797 out of 1000


In [19]:
skfold = StratifiedKFold(n_splits=10)

for std in [0.2, 0.4,  0.6,  0.8, 1]:
  average_results = []
  for i, (train, test) in enumerate(skfold.split(X, y), start=1):
    x_train, x_test = X[train], X[test]
    y_train, y_test = y[train], y[test]

    pnn_network = PNN(std=0.1, verbose=False)
    pnn_network.train(x_train, y_train)
    result = pnn_network.predict(x_test)

    n_predicted_correctly = np.sum(result == y_test)
    n_test_samples = test.size

    average_results.append(np.sum(result == y_test) /float(len(result)))

    print("Test #{:<2}: Guessed {} out of {}".format(
        i, n_predicted_correctly, n_test_samples))
    
print(std, np.average(average_results))


Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000


Test #10: Guessed 797 out of 1000


Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000


Test #10: Guessed 797 out of 1000


Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000


Test #10: Guessed 797 out of 1000


Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000


Test #10: Guessed 797 out of 1000


Test #1 : Guessed 796 out of 1000


Test #2 : Guessed 796 out of 1000


Test #3 : Guessed 796 out of 1000


Test #4 : Guessed 796 out of 1000


Test #5 : Guessed 796 out of 1000


Test #6 : Guessed 796 out of 1000


Test #7 : Guessed 796 out of 1000


Test #8 : Guessed 797 out of 1000


Test #9 : Guessed 797 out of 1000
Test #10: Guessed 797 out of 1000
1 0.7962999999999999


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, result)
print(cm)
accuracy_score(y_test, result)

[[797   0]
 [203   0]]


0.797

# For std 1 we get accuracy 79.7%